### ISSUE TITLE
Ubuntu如何配置python？

### ISSUE THREAD

**Issue by muniseven** [erguotou520/electron-ssr#145]
python2.7和python3.4还是什么版本的python？sudo apt-get后就可以了吗？
请原谅我在issues里提问......但tg在哪连链接都没有啊.......

**Comment by muniseven** [comment]
还有windows的pac文件在哪个文件夹

**Comment by muniseven** [comment]
```
2018-06-16 00:51:13 <info> main.js:1 () file ensured
2018-06-16 00:51:35 <debug> main.js:1 (EventEmitter.<anonymous>) start download ssr
2018-06-16 00:51:39 <debug> main.js:1 () ssr download success
2018-06-16 00:52:02 <debug> main.js:1 (o) run command: python C:\Users\Ultra\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s jp02.ssrpink.fun -p 58040 -m aes-192-ctr -O auth_chain_a -o http_simple -g jd.hk -b 127.0.0.1 -l 1080
2018-06-16 00:52:02 <debug> main.js:1 (Server.<anonymous>) pac server listen at: 127.0.0.1:2333
2018-06-16 00:52:02 <debug> main.js:1 (Server.<anonymous>) http proxy server listen at: 127.0.0.1:12333
IPv6 support
Traceback (most recent call last):
  File "C:\Users\Ultra\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\Ultra\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\Ultra\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\Ultra\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\Ultra\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\Ultra\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\Ultra\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\Ultra\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\openssl.py", line 89, in __init__
    load_openssl()
  File "C:\Users\Ultra\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\openssl.py", line 41, in load_openssl
    raise Exception('libcrypto(OpenSSL) not found')
Exception: libcrypto(OpenSSL) not found
2018-06-16 00:52:34 <debug> main.js:1 () start download pac
2018-06-16 00:56:09 <debug> main.js:1 () start download pac
```
这是日志.......看不懂哪里有问题，就是连不上，求教

**Comment by muniseven** [comment]
任务栏上的纸飞机显示undefined，什么意思啊

**Comment by erguotou520** [comment]
1. 别人好像建议python 3
2. tg暂时已关闭，采用邀请模式
3. `C:\Users\Ultra\AppData\Roaming\electron-ssr\pac.txt`
4. 日志显示却少加密库，对于却少依赖的问题请自行解决（目前，后续会换libev版本，应该没有这种问题）
5. 请截图
