### ISSUE TITLE
特定的配置无法工作

### ISSUE THREAD

**Issue by CGQAQ** [erguotou520/electron-ssr#155]
## Your os
Fedora 28 TwentyEight

## The version of electron-ssr
0.2.3

## What's the problem
特定配置无法工作，但在手机版ssr上可以正常使用，比如chacha20-ietf+auth-aes128-md5+http-simple

## App log here

2018-07-02 17:55:15 <log> main.js:1 () Kill python client
2018-07-02 17:55:15 <debug> main.js:1 (o) run command: python /home/jason/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s xxxxxx -p xxxxx -m chacha20-ietf -O auth_aes128_md5 -o http_simple -g jd.hk -b 127.0.0.1 -l 11080
IPv6 support
Traceback (most recent call last):
  File "/home/jason/.config/electron-ssr/shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "/home/jason/.config/electron-ssr/shadowsocksr/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "/home/jason/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 299, in get_config
    check_config(config, is_local)
  File "/home/jason/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/home/jason/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/home/jason/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/home/jason/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/home/jason/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 71, in __init__
    load_libsodium()
  File "/home/jason/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found

**Comment by erguotou520** [comment]
请注意最后一句话 在FAQ中有解决方法

**Comment by CGQAQ** [comment]
解决了  谢谢sudo dnf install libsodium
