### ISSUE TITLE
Exception: libcrypto(OpenSSL) not found 错误如何解决?

### ISSUE THREAD

**Issue by AmelieNet** [erguotou520/electron-ssr#158]
## Your os
Windows10

## The version of electron-ssr
v.0.2.3

## What's the problem
链接不上网络,应用日志如下,请问端口是SOCKS5 1080吧?

## App log here
```
Traceback (most recent call last):
  File "C:\Users\Ameli\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\Ameli\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\Ameli\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\Ameli\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\Ameli\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\Ameli\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\Ameli\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\Ameli\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\openssl.py", line 89, in __init__
    load_openssl()
  File "C:\Users\Ameli\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\openssl.py", line 41, in load_openssl
    raise Exception('libcrypto(OpenSSL) not found')
Exception: libcrypto(OpenSSL) not found
```

**Comment by erguotou520** [comment]
请先安装openssl的库，参考 https://slproweb.com/products/Win32OpenSSL.html
