### ISSUE TITLE
Windows 10 无法代理

### ISSUE THREAD

**Issue by Zheng404** [erguotou520/electron-ssr#195]
## Your os

Windows 10 1803
## The version of electron-ssr

0.2.4
## What's the problem

开启代理后，无法使用，同样的代理服务器，使用老版ShadowsocksR4.70可正常代理并访问墙外网站，但本软件提示已经开启代理，却无法访问墙外网站。
## App log here

2018-09-13 12:26:16 <info> main.js:1 () file ensured
2018-09-13 12:26:17 <info> main.js:1 (u) Register shortcut: toggleMenu, CommandOrControl+Shift+B
2018-09-13 12:26:17 <debug> main.js:1 (o) run command: python C:\Users\15352\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s 203.218.253.247 -p 12002 -m aes-256-cfb -O origin -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2018-09-13 12:26:17 <debug> main.js:1 (Server.<anonymous>) pac server listen at: 127.0.0.1:2333
2018-09-13 12:26:17 <debug> main.js:1 (Server.<anonymous>) http proxy server listen at: 127.0.0.1:12333
2018-09-13 12:26:17 INFO     util.py:85 loading libcrypto from C:\Windows\system32\libcrypto.dll
2018-09-13 12:26:17 INFO     local.py:50 local start with protocol[origin] password [b'3Lewf4pzv'] method [aes-256-cfb] obfs [tls1.2_ticket_auth] obfs_param []
2018-09-13 12:26:17 INFO     local.py:54 starting local at 127.0.0.1:1080
2018-09-13 12:26:17 INFO     asyncdns.py:324 dns server: [('8.8.4.4', 53), ('8.8.8.8', 53)]

**Comment by erguotou520** [comment]
应该是PAC的问题，试着换全局模式

**Comment by Zheng404** [comment]
试过了，全局模式也不行，网银插件会提示在代理，但浏览器仍旧打不开相关网站

**Comment by erguotou520** [comment]
请尝试使用curl命令行等其它方式验证是否代理成功，因为不能代理的原因有很多，但是从你的日志来看软件运行正常

**Comment by zyd16888** [comment]
我的也是同样的问题，pac也更新了，但还是不能连接  2333

**Comment by ylf0925** [comment]
+1

**Comment by kyan001** [comment]
+1 
在 PC 上 PAC 模式和全局模式都不行。Chrome 在全局模式中会卡在“正在等待代理隧道的响应”的步骤。

**Comment by yangyzp** [comment]
我这边win7，原版ssr没问题，
这个版本的无法代理

**Comment by brady2037** [comment]
win10 也是无法使用，各种改设置都没办法，用其他的ssr客户端可以

**Comment by JohnFreeman9** [comment]
由于Log输出确实不够完整，自查时完全定位不到问题发生在哪里，当前同样出现即使PAC更新能够成功，但是软件不论给不给管理员权限均无法正常运行的问题。
同时，如果尝试在混淆参数中使用UA头设置，由于UA头带\n换行符等，似乎会出现can't concat str to bytes的错误。

**Comment by orchie** [comment]
最新版 2.6 win10下还是无法使用  
```
2019-01-30 12:02:17:890 [info] Checking for update
2019-01-30 12:02:18:081 [info] last update time: Wed Jan 30 2019 12:02:18 GMT+0800 (中国标准时间)
2019-01-30 12:02:18:112 [info] next subscribe update time: Thu Jan 31 2019 12:02:18 GMT+0800 (中国标准时间)
2019-01-30 12:02:25:770 [info] Update for version 0.2.6 is not available (latest version: 0.2.6, downgrade is disallowed).
2019-01-30 12:02:39:947 [info] run command: python C:\Users\Administrator\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s www.google.com -p 1 -k ****** -m chacha20 -O auth_chain_a -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2019-01-30 12:02:39:954 [info] pac server listen at: 127.0.0.1:2333
2019-01-30 12:02:39:955 [info] http proxy server listen at: 127.0.0.1:12333
2019-01-30 12:02:40:270 [info] IPv6 support

2019-01-30 12:02:40:273 [error] Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\Administrator\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\Administrator\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\Administrator\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\Administrator\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\Administrator\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\Administrator\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\Administrator\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "C:\Users\Administrator\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 40, in load_libsodium
    'libsodium')
  File "C:\Users\Administrator\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\util.py", line 83, in find_library
    lib = CDLL(path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 ������Ч�� Win32 Ӧ�ó���
```
@erguotou520

**Comment by BestRicky** [comment]
+1
----------------------------
2019-02-19 12:43:09:394 [info] Checking for update
2019-02-19 12:43:10:722 [info] Generated new staging user ID: 4944e467-3162-5ae3-83c8-27ef71f07781
2019-02-19 12:43:16:761 [info] start download ssr
2019-02-19 12:43:18:516 [info] ssr download success
2019-02-19 12:43:18:547 [error] Error: Command failed: C:\Program Files (x86)\electron-ssr\sysproxy.exe pac ""
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:603:13)
    at execSync (child_process.js:643:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:687:22)
    at j (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56151)
    at P (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56432)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:77481)
    at e.__tryOrUnsub (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:11312)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:10590)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:17837)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at m (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:55286)

2019-02-19 12:43:19:395 [info] Update for version 0.2.6 is not available (latest version: 0.2.6, downgrade is disallowed).
2019-02-19 12:43:20:571 [error] Error: Command failed: C:\Program Files (x86)\electron-ssr\sysproxy.exe pac ""
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:603:13)
    at execSync (child_process.js:643:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:687:22)
    at j (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56151)
    at P (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56432)
    at App.<anonymous> (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:84124)
    at emitOne (events.js:120:20)
    at App.emit (events.js:210:7)
    at App.emitter.emit.args [as emit] (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\@sentry\electron\src\main\integrations\electron.ts:65:14)
    at J (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:58849)
    at MenuItem.click (C:\Program Files (x86)\electron-ssr\resources\electron.asar\browser\api\menu-item.js:52:9)
    at Function.executeCommand (C:\Program Files (x86)\electron-ssr\resources\electron.asar\browser\api\menu.js:34:15)

2019-02-19 12:49:32:139 [info] Checking for update
2019-02-19 12:49:34:456 [error] Error: Error: net::ERR_NAME_NOT_RESOLVED
    at CancellationToken.createPromise (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
    at ElectronHttpExecutor.doApiRequest (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:84:30)
    at ElectronHttpExecutor.request (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:74:17)
    at GitHubProvider.httpRequest (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\Provider.ts:29:26)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\GitHubProvider.ts:38:41
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\GitHubProvider.ts:35:25)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:308:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater.getUpdateInfo (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:298:32)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:312:35
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:311:34)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:283:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:278:33)
    at NsisUpdater.checkForUpdates (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:217:35)
    at W (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:59493)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:83314
    at <anonymous>
2019-02-19 12:49:36:226 [info] run command: python C:\Users**AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s 127.0.0.1 -p 8388 -k ****** -m aes-256-cfb -O origin -o plain -b 127.0.0.1 -l 1080
2019-02-19 12:49:36:231 [info] pac server listen at: 127.0.0.1:2333
2019-02-19 12:49:36:231 [info] http proxy server listen at: 127.0.0.1:12333
2019-02-19 12:49:36:540 [error] 2019-02-19 12:49:36 WARNING  shell.py:113 warning: server set to listen on 127.0.0.1:8388, are you sure?

2019-02-19 12:49:36:556 [info] IPv6 support

2019-02-19 12:49:36:556 [error] Traceback (most recent call last):
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\crypto\openssl.py", line 89, in __init__
    load_openssl()
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\crypto\openssl.py", line 41, in load_openssl
    raise Exception('libcrypto(OpenSSL) not found')
Exception: libcrypto(OpenSSL) not found

2019-02-19 12:49:37:584 [error] Error: Command failed: C:\Program Files (x86)\electron-ssr\sysproxy.exe pac ""
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:603:13)
    at execSync (child_process.js:643:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:687:22)
    at j (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56151)
    at P (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56432)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:77481)
    at e.__tryOrUnsub (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:11312)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:10590)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:17837)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at m (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:55286)

2019-02-19 12:49:37:586 [info] Kill client
2019-02-19 12:49:37:587 [info] pac server closed.
2019-02-19 12:49:37:587 [info] http proxy server closed.
2019-02-19 12:49:37:590 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: kill ESRCH
2019-02-19 12:49:37:598 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_NAME_NOT_RESOLVED
2019-02-19 12:49:37:598 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_NAME_NOT_RESOLVED
2019-02-19 12:49:37:600 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_NAME_NOT_RESOLVED
2019-02-19 12:49:37:600 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_NAME_NOT_RESOLVED
2019-02-19 12:49:42:601 [error] 进程 14612 可能无法关闭
2019-02-19 12:51:51:828 [info] Kill client
2019-02-19 12:51:51:844 [info] pac server listen at: 127.0.0.1:2333
2019-02-19 12:51:51:844 [info] http proxy server listen at: 127.0.0.1:12333
2019-02-19 12:51:51:844 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: kill ESRCH
2019-02-19 12:51:52:889 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-02-19 12:51:52:889 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-02-19 12:51:56:853 [error] 进程 14612 可能无法关闭
2019-02-19 12:58:30:879 [error] Error: Command failed: C:\Program Files (x86)\electron-ssr\sysproxy.exe pac ""
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:603:13)
    at execSync (child_process.js:643:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:687:22)
    at j (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56151)
    at P (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56432)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:77481)
    at e.__tryOrUnsub (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:11312)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:10590)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:17837)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at m (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:55286)

2019-02-19 12:58:30:883 [info] Kill client
2019-02-19 12:58:30:886 [info] pac server closed.
2019-02-19 12:58:30:886 [info] http proxy server closed.
2019-02-19 12:58:30:886 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: kill EPERM
2019-02-19 12:58:31:689 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-02-19 12:58:31:690 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-02-19 12:58:32:293 [info] Kill client
2019-02-19 12:58:32:304 [info] pac server listen at: 127.0.0.1:2333
2019-02-19 12:58:32:304 [info] http proxy server listen at: 127.0.0.1:12333
2019-02-19 12:58:32:305 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: kill EPERM
2019-02-19 12:58:32:568 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-02-19 12:58:32:569 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting

**Comment by rainyl** [comment]
同样的问题

**Comment by daihengfei** [comment]
安装目录不要带空格。
