### ISSUE TITLE
win10 X64  企业版无法正常使用

### ISSUE THREAD

**Issue by pepsigold** [erguotou520/electron-ssr#207]
## Your os
win10 X64  企业版更新到20181007 fix

## The version of electron-ssr
  electron-ssr version  0.2.4

## What's the problem
无论是用全局还是PAC模式均无法访问谷歌Facebook等网站，
用pac模式可以访问国内网站，但国外网站无法访问。
用全局模式模式可以访问国内网站，但国外网站无法访问。
用
https://github.com/shadowsocks/shadowsocks-windows
以及
https://github.com/shadowsocks/shadowsocks-windows/compare/4.1.2...master
这个无论什么模式都可以使用我的SSR订阅自动更新的服务器，正常使用

## App log here 日志部分敏感信息已修改
2018-10-07 17:10:26 <info> main.js:1 () file ensured
2018-10-07 17:10:26 <info> main.js:1 (u) Register shortcut: toggleMenu, CommandOrControl+Shift+B
2018-10-07 17:10:33 <debug> main.js:1 (EventEmitter.<anonymous>) start download ssr
2018-10-07 17:10:36 <debug> main.js:1 () ssr download success
2018-10-07 17:11:06 <info> main.js:1 () file ensured
2018-10-07 17:11:07 <info> main.js:1 (u) Register shortcut: toggleMenu, CommandOrControl+Shift+B
2018-10-07 17:11:33 <debug> main.js:1 (o) run command: python C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s us1.telegram-ssr123ssr123.com -p 8546 -m aes-256-cfb -O auth_sha1_v4 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2018-10-07 17:11:41 <debug> main.js:1 (Server.<anonymous>) pac server listen at: 127.0.0.1:2333
2018-10-07 17:11:41 <debug> main.js:1 (Server.<anonymous>) http proxy server listen at: 127.0.0.1:12333
2018-10-07 17:11:41 INFO     util.py:85 loading libcrypto from C:\WINDOWS\system32\libcrypto.dll
2018-10-07 17:11:41 INFO     local.py:50 local start with protocol[auth_sha1_v4] password [b'G00dss'] method [aes-256-cfb] obfs [tls1.2_ticket_auth] obfs_param []
2018-10-07 17:11:41 INFO     local.py:54 starting local at 127.0.0.1:1080
2018-10-07 17:11:41 INFO     asyncdns.py:324 dns server: [('8.8.4.4', 53), ('8.8.8.8', 53)]
2018-10-07 17:12:40 <log> main.js:1 () Kill python client
2018-10-07 17:12:40 <debug> main.js:1 (o) run command: python C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s ssr123hk.ssr123.com -p 8546 -m chacha20 -O auth_chain_a -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
IPv6 support
Traceback (most recent call last):
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
2018-10-07 17:12:45 <debug> main.js:1 () start download pac
2018-10-07 17:13:29 <debug> main.js:1 () start download pac
2018-10-07 17:13:49 <log> main.js:1 () Kill python client
2018-10-07 17:13:54 <error> main.js:1 (Timeout._onTimeout) 进程 10080 可能无法关闭
2018-10-07 17:13:54 <debug> main.js:1 (o) run command: python C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s ssr123hk1.ssr123.com -p 8546 -m chacha20 -O auth_chain_a -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
IPv6 support
Traceback (most recent call last):
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
2018-10-07 17:14:47 <log> main.js:1 () Kill python client
2018-10-07 17:14:52 <error> main.js:1 (Timeout._onTimeout) 进程 1996 可能无法关闭
2018-10-07 17:14:52 <debug> main.js:1 (o) run command: python C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s sg1.telegram-ssr123ssr123.com -p 8546 -m chacha20 -O auth_chain_a -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
IPv6 support
Traceback (most recent call last):
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
2018-10-07 17:16:07 <debug> main.js:1 () start download pac
2018-10-07 17:16:26 <log> main.js:1 () Kill python client
2018-10-07 17:16:26 <debug> main.js:1 () http proxy server closed.
2018-10-07 17:16:26 <debug> main.js:1 () pac server closed.
2018-10-07 17:16:33 <info> main.js:1 () file ensured
2018-10-07 17:16:33 <info> main.js:1 (u) Register shortcut: toggleMenu, CommandOrControl+Shift+B
2018-10-07 17:16:33 <debug> main.js:1 (o) run command: python C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s sg1.telegram-ssr123ssr123.com -p 8546 -m chacha20 -O auth_chain_a -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2018-10-07 17:16:33 <debug> main.js:1 (Server.<anonymous>) pac server listen at: 127.0.0.1:2333
2018-10-07 17:16:33 <debug> main.js:1 (Server.<anonymous>) http proxy server listen at: 127.0.0.1:12333
IPv6 support
Traceback (most recent call last):
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
2018-10-07 21:28:30 <info> main.js:1 () file ensured
2018-10-07 21:28:31 <info> main.js:1 (u) Register shortcut: toggleMenu, CommandOrControl+Shift+B
2018-10-07 21:28:31 <debug> main.js:1 (o) run command: python C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s sg1.telegram-ssr123ssr123.com -p 8546 -m chacha20 -O auth_chain_a -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2018-10-07 21:28:31 <debug> main.js:1 (Server.<anonymous>) pac server listen at: 127.0.0.1:2333
2018-10-07 21:28:31 <debug> main.js:1 (Server.<anonymous>) http proxy server listen at: 127.0.0.1:12333
IPv6 support
Traceback (most recent call last):
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
2018-10-07 21:31:16 <log> main.js:1 () Kill python client
2018-10-07 21:31:20 <log> main.js:1 () Kill python client
2018-10-07 21:31:20 <debug> main.js:1 () pac server closed.
2018-10-07 21:31:20 <debug> main.js:1 () http proxy server closed.
2018-10-07 21:31:21 <error> main.js:1 (Timeout._onTimeout) 进程 8632 可能无法关闭
2018-10-07 21:31:21 <debug> main.js:1 (o) run command: python C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s ssr123hk.ssr123.com -p 8546 -m chacha20 -O auth_chain_a -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2018-10-07 21:31:21 <log> main.js:1 () Kill python client
2018-10-07 21:31:21 <debug> main.js:1 (Server.<anonymous>) pac server listen at: 127.0.0.1:2333
2018-10-07 21:31:21 <debug> main.js:1 (Server.<anonymous>) http proxy server listen at: 127.0.0.1:12333
2018-10-07 21:31:21 <debug> main.js:1 (o) run command: python C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s ssr123hk.ssr123.com -p 8546 -m chacha20 -O auth_chain_a -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
IPv6 support
Traceback (most recent call last):
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
2018-10-07 21:31:25 <error> main.js:1 (Timeout._onTimeout) 进程 3632 可能无法关闭
2018-10-07 21:33:47 <debug> main.js:1 () start download pac
2018-10-07 21:33:58 <debug> main.js:1 () pac server closed.
2018-10-07 21:33:58 <debug> main.js:1 () http proxy server closed.
2018-10-07 21:34:01 <debug> main.js:1 (Server.<anonymous>) pac server listen at: 127.0.0.1:2333
2018-10-07 21:34:01 <debug> main.js:1 (Server.<anonymous>) http proxy server listen at: 127.0.0.1:12333
2018-10-07 21:36:33 <log> main.js:1 () Kill python client
2018-10-07 21:36:33 <debug> main.js:1 () http proxy server closed.
2018-10-07 21:36:33 <debug> main.js:1 () pac server closed.
2018-10-07 21:36:38 <error> main.js:1 (Timeout._onTimeout) 进程 3632 可能无法关闭
2018-10-07 21:41:30 <log> main.js:1 () Kill python client
2018-10-07 21:41:49 <info> main.js:1 () file ensured
2018-10-07 21:41:50 <info> main.js:1 (u) Register shortcut: toggleMenu, CommandOrControl+Shift+B
2018-10-07 21:42:25 <debug> main.js:1 (o) run command: python C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s ssr123hk.ssr123.com -p 8546 -m chacha20 -O auth_chain_a -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2018-10-07 21:42:25 <debug> main.js:1 (Server.<anonymous>) pac server listen at: 127.0.0.1:2333
2018-10-07 21:42:25 <debug> main.js:1 (Server.<anonymous>) http proxy server listen at: 127.0.0.1:12333
IPv6 support
Traceback (most recent call last):
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "C:\Users\AliBaba\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
2018-10-07 21:43:47 <log> main.js:1 () Kill python client
2018-10-07 21:43:47 <debug> main.js:1 () http proxy server closed.
2018-10-07 21:43:47 <debug> main.js:1 () pac server closed.

**Comment by erguotou520** [comment]
请留意日志里的`libsodium not found`报错，在FAQ里有相关介绍
