### ISSUE TITLE
Segmentation fault on Manjaro Linux

### ISSUE THREAD

**Issue by NWindy5** [erguotou520/electron-ssr#239]
## Your os
kernel version 4.19.2-1  MANJARO x86_64

## The version of electron-ssr

0.2.4-2
build from aur repo [electron-ssr](https://aur.archlinux.org/packages/electron-ssr/)

## What's the problem

Segmentation fault

## App log here

stack backtrace

```
#0  0x000000000371e002 in  ()
#1  0x0000000003f8a709 in __start_google_malloc ()
#2  0x00000000037949ec in malloc ()
#3  0x00007ffff4469f49 in g_file_get_contents () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff5dfb1e4 in g_io_modules_scan_all_in_directory_with_scope () at /usr/lib/libgio-2.0.so.0
#5  0x00007ffff5dff01d in  () at /usr/lib/libgio-2.0.so.0
#6  0x00007ffff5dff484 in  () at /usr/lib/libgio-2.0.so.0
#7  0x00007ffff5e161df in g_file_new_for_path () at /usr/lib/libgio-2.0.so.0
#8  0x00007fffe8e8ba4f in  () at /usr/lib/libibus-1.0.so.5
#9  0x00007ffff5ca707b in  () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff5ca7eb4 in g_object_new_valist () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff5ca884a in g_object_new () at /usr/lib/libgobject-2.0.so.0
#12 0x00007fffe8e89467 in ibus_bus_new_async_client () at /usr/lib/libibus-1.0.so.5
#13 0x00007fffe9783914 in  () at /usr/lib/gtk-3.0/3.0.0/immodules/im-ibus.so
#14 0x00007ffff5c8a30c in g_type_class_ref () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff5ca8799 in g_object_new_with_properties () at /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff5ca887a in g_object_new () at /usr/lib/libgobject-2.0.so.0
#17 0x00007fffe9784544 in ibus_im_context_new () at /usr/lib/gtk-3.0/3.0.0/immodules/im-ibus.so
#18 0x00007ffff6406ec3 in  () at /usr/lib/libgtk-x11-2.0.so.0
#19 0x00007ffff640787a in  () at /usr/lib/libgtk-x11-2.0.so.0
#20 0x00007ffff6407a66 in  () at /usr/lib/libgtk-x11-2.0.so.0
#21 0x00007ffff63ad751 in  () at /usr/lib/libgtk-x11-2.0.so.0
#22 0x00007ffff5ca33d5 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#23 0x00007ffff5c90348 in  () at /usr/lib/libgobject-2.0.so.0
#24 0x00007ffff5c9401e in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#25 0x00007ffff5c94a80 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#26 0x00007ffff6540582 in gtk_widget_realize () at /usr/lib/libgtk-x11-2.0.so.0
#27 0x00007ffff6541928 in gtk_widget_set_parent () at /usr/lib/libgtk-x11-2.0.so.0
#28 0x00007ffff636afab in  () at /usr/lib/libgtk-x11-2.0.so.0
#29 0x00007ffff5ca33d5 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#30 0x00007ffff5c90348 in  () at /usr/lib/libgobject-2.0.so.0
#31 0x00007ffff5c9401e in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#32 0x00007ffff5c94a80 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#33 0x0000000000911d90 in  ()
#34 0x0000000000911528 in  ()
#35 0x00000000009056d0 in  ()
#36 0x000000000090545b in  ()
#37 0x0000000003f5d1fb in brightray::BrowserMainParts::ToolkitInitialized() ()
#38 0x0000000000a8652c in  ()
#39 0x00000000009f7405 in  ()
#40 0x0000000000ae8b62 in  ()
#41 0x00000000010de578 in  ()
#42 0x00000000036ce02f in  ()
#43 0x00000000010de7e2 in  ()
#44 0x0000000003de5e08 in main ()
```

I don't know how to properly debug a electron app so I used gdb on the executable

**Comment by NWindy5** [comment]
debugging log with electron
```
App threw an error during load
/opt/electron-ssr/electron-ssr:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { ELF
                                                                                                                                                           ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:287:12)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:328:5)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:365:3)
A JavaScript error occurred in the main process
Uncaught Exception:
/opt/electron-ssr/electron-ssr:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { ELF
                                                                                                                                                           ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:287:12)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:328:5)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:365:3)
```

**Comment by NWindy5** [comment]
The problem disappeared after I removed ibus. I think this issue has nothing to do with your code but I'm not sure yet.

**Comment by NWindy5** [comment]
是我环境设置的问题, closed
