### ISSUE TITLE
 npm run dev:Error: Cannot find module 'tree-kill'

### ISSUE THREAD

**Issue by V0idk** [erguotou520/electron-ssr#25]
$ npm run dev

> electron-ssr@0.1.0 dev /home/..../electron-ssr-develop
> node tasks/runner.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'tree-kill'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zhong/下载/electron-ssr-develop/tasks/runner.js:8:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by erguotou520** [comment]
Refer to
https://github.com/erguotou520/electron-ssr/blob/develop/package.json#L48
所以是你安装的不完整导致的，请删除后重新安装
```bash
# in workspace folder
rm -rf node_modules
npm i  # or cnpm i
```
