### ISSUE TITLE
Windows上导入Linux的gui-config会把ssr-python目录给变化

### ISSUE THREAD

**Issue by Javi2004** [erguotou520/electron-ssr#264]
## Your os

Windows 10 专业版 1803

## The version of electron-ssr

0.2.5

## What's the problem

如果将Linux的guiconfig导入Windows中，他会直接炸掉。如图所示

![image](https://user-images.githubusercontent.com/32459390/50733057-0f072e80-11c1-11e9-9a43-358bca69db30.png)

## App log here

2019-01-06 12:15:06:121 [info] Checking for update
2019-01-06 12:15:07:824 [info] Generated new staging user ID: f31a5b74-be25-5865-894e-f286f5f96fd7
2019-01-06 12:15:11:009 [error] Error: Error: No latest version, please ensure that user, package and repository correctly configured. Or at least one version is published. HttpError: 404 Not Found
"method: undefined url: https://api.bintray.com/packages/erguotou520/generic/electron-ssr/versions/_latest\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "connection": [
    "keep-alive"
  ],
  "content-encoding": [
    "gzip"
  ],
  "content-type": [
    "application/json"
  ],
  "date": [
    "Sun, 06 Jan 2019 04:15:25 GMT"
  ],
  "server": [
    "nginx"
  ],
  "transfer-encoding": [
    "chunked"
  ]
}
    at createHttpError (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:32:10)
    at ElectronHttpExecutor.handleResponse (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:130:14)
    at ClientRequest.request.doRequest.response (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:87:16)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at URLRequest.ClientRequest.urlRequest.on (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\electron.asar\browser\api\net.js:209:12)
    at emitOne (events.js:115:13)
    at URLRequest.emit (events.js:210:7)
From previous event:
    at CancellationToken.createPromise (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
    at ElectronHttpExecutor.doApiRequest (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:84:30)
    at ElectronHttpExecutor.request (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:74:17)
    at BintrayClient.bintrayRequest (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\bintray.ts:55:40)
    at BintrayClient.getVersion (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\bintray.ts:59:17)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\BintrayProvider.ts:25:38
    at Generator.next (<anonymous>)
From previous event:
    at BintrayProvider.getLatestVersion (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\BintrayProvider.ts:23:25)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:308:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater.getUpdateInfo (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:298:32)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:312:35
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:311:34)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:283:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:278:33)
    at NsisUpdater.checkForUpdates (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:217:35)
    at t.a (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\dist\electron\main.js:1:35312)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\dist\electron\main.js:1:54459
    at <anonymous>
    at createHttpError (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:32:10)
    at ElectronHttpExecutor.handleResponse (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:130:14)
    at ClientRequest.request.doRequest.response (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:87:16)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at URLRequest.ClientRequest.urlRequest.on (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\electron.asar\browser\api\net.js:209:12)
    at emitOne (events.js:115:13)
    at URLRequest.emit (events.js:210:7)
    at CancellationToken.createPromise (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
    at ElectronHttpExecutor.doApiRequest (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:84:30)
    at ElectronHttpExecutor.request (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:74:17)
    at BintrayClient.bintrayRequest (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\bintray.ts:55:40)
    at BintrayClient.getVersion (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\bintray.ts:59:17)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\BintrayProvider.ts:25:38
    at Generator.next (<anonymous>)
    at BintrayProvider.getLatestVersion (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\BintrayProvider.ts:23:25)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:308:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
    at NsisUpdater.getUpdateInfo (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:298:32)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:312:35
    at Generator.next (<anonymous>)
    at NsisUpdater.doCheckForUpdates (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:311:34)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:283:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
    at NsisUpdater._checkForUpdates (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:278:33)
    at NsisUpdater.checkForUpdates (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:217:35)
    at t.a (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\dist\electron\main.js:1:35312)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\dist\electron\main.js:1:54459
    at <anonymous>
    at newError (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\index.ts:29:17)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\BintrayProvider.ts:39:15
    at Generator.throw (<anonymous>)
From previous event:
    at BintrayProvider.getLatestVersion (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\BintrayProvider.ts:23:25)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:308:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater.getUpdateInfo (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:298:32)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:312:35
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:311:34)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:283:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:278:33)
    at NsisUpdater.checkForUpdates (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:217:35)
    at t.a (C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\dist\electron\main.js:1:35312)
    at C:\Users\Admin\AppData\Local\Programs\electron-ssr\resources\app.asar\dist\electron\main.js:1:54459
    at <anonymous>

**Comment by erguotou520** [comment]
请重新选择ssr-python目录
