### ISSUE TITLE
Win10 无法连接，关于Crypto的报错

### ISSUE THREAD

**Issue by JSpringYC** [erguotou520/electron-ssr#268]
## Your os
Windows 10 X64

## The version of electron-ssr
0.2.5

## What's the problem
无法连接SS服务器

## App log here

```
2019-01-08 13:55:31 <info> main.js:1 () file ensured
2019-01-08 13:55:31 <info> main.js:1 (u) Register shortcut: toggleMenu, CommandOrControl+Shift+B
2019-01-08 13:55:36 <debug> main.js:1 (o) run command: python C:\Users\jiangyc\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s hkt3.hktpccw.tk -p 443 -m aes-256-cfb -O auth_aes128_sha1 -G 18736:n1BJow -o tls1.2_ticket_auth -g 5829118736.cloudflare.com -b 127.0.0.1 -l 1080
2019-01-08 13:55:36 <debug> main.js:1 (Server.<anonymous>) pac server listen at: 127.0.0.1:2333
2019-01-08 13:55:36 <debug> main.js:1 (Server.<anonymous>) http proxy server listen at: 127.0.0.1:12333
Traceback (most recent call last):

  File "C:\Users\jiangyc\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>

    main()

  File "C:\Users\jiangyc\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main

    config = shell.get_config(True)

  File "C:\Users\jiangyc\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config

    check_config(config, is_local)

  File "C:\Users\jiangyc\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config

    encrypt.try_cipher(config['password'], config['method'])

  File "C:\Users\jiangyc\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher

    Encryptor(key, method)

  File "C:\Users\jiangyc\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__

    random_string(self._method_info[1]))

  File "C:\Users\jiangyc\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher

    return m[2](method, key, iv, op)

  File "C:\Users\jiangyc\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\openssl.py", line 89, in __init__

    load_openssl()

  File "C:\Users\jiangyc\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\openssl.py", line 41, in load_openssl

    raise Exception('libcrypto(OpenSSL) not found')

Exception: libcrypto(OpenSSL) not found

IPv6 support
```

**Comment by erguotou520** [comment]
自行安装 libcrypto
