### ISSUE TITLE
ubuntu 16.04 rpm包转换deb以后遇到了这个问题

### ISSUE THREAD

**Issue by GuaiYiHu** [erguotou520/electron-ssr#27]
caught Exception:
TypeError: Cannot read property 'host' of undefined
    at Object.module.exports.run (/opt/ShadowsocksR客户端/resources/app.asar/client.js:54:29)
    at App.app.on (/opt/ShadowsocksR客户端/resources/app.asar/electron.js:109:14)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

**Comment by erguotou520** [comment]
额。。。看错误日志没道理啊 试试管理员权限运行？删除掉配置文件 重新以管理员权限运行下试试？

**Comment by erguotou520** [comment]
大概知道原因了，是配置文件的问题，我做下容错，你这个可以先备份下配置，然后删除配置文件重新初始化

**Comment by GuaiYiHu** [comment]
谢谢，朋友

**Comment by erguotou520** [comment]
`0.1.1`版本已修复该问题，请测试

**Comment by erguotou520** [comment]
先close掉了，如果有问题再开

**Comment by GuaiYiHu** [comment]
已测试修复，感谢作者
