### ISSUE TITLE
0.2.6弹窗显示检查更新失败

### ISSUE THREAD

**Issue by rxlfnng** [erguotou520/electron-ssr#288]

**Comment by rxlfnng** [comment]
os: win7 64位
v0.2.6
弹窗显示检查更新失败 Error: net::ERR_CONNECTION_CLOSED
    at CancellationToken.createPromise...

日志：2019-02-10 20:16:14:218 [error] 2019-02-10 20:16:14 ERROR    tcprelay.py:1035 [Errno 10061] Unknown error

2019-02-10 20:16:14:220 [error] 2019-02-10 20:16:14 ERROR    tcprelay.py:1037 remote error, when connect to github-production-release-asset-2e65be.s3.amazonaws.com:443

2019-02-10 20:16:15:805 [error] 2019-02-10 20:16:15 ERROR    tcprelay.py:1035 [Errno 10061] Unknown error
2019-02-10 20:16:15 ERROR    tcprelay.py:1037 remote error, when connect to github-production-release-asset-2e65be.s3.amazonaws.com:443

2019-02-10 20:16:15:817 [error] Error: Error: net::ERR_CONNECTION_CLOSED
    at CancellationToken.createPromise (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
    at ElectronHttpExecutor.doApiRequest (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:84:30)
    at ElectronHttpExecutor.request (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:74:17)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\GitHubProvider.ts:74:38
From previous event:
    at GitHubProvider.getLatestVersion (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\GitHubProvider.ts:35:25)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:308:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater.getUpdateInfo (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:298:32)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:312:35
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:311:34)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:283:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:278:33)
    at NsisUpdater.checkForUpdates (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:217:35)
    at W (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:59493)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:83314
    at <anonymous>

**Comment by erguotou520** [comment]
检测失败就手动更新吧
