### ISSUE TITLE
win10 代理出错

### ISSUE THREAD

**Issue by zhouzhu85** [erguotou520/electron-ssr#294]
2019-02-14 10:09:11:863 [info] Checking for update
2019-02-14 10:09:12:065 [error] Error: Command failed: C:\Program Files (x86)\electron-ssr\sysproxy.exe pac http://127.0.0.1:2333/proxy.pac
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:603:13)
    at execSync (child_process.js:643:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:687:22)
    at j (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56151)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56722
    at E (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56727)
    at M (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:57182)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:77453)
    at e.__tryOrUnsub (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:11312)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:10590)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:17837)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)

2019-02-14 10:09:12:105 [info] run command: python C:\Users\Administrator\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s 35.221.69.73 -p 6666 -k ****** -m rc4-md5 -O origin -o plain -b 127.0.0.1 -l 1080
2019-02-14 10:09:12:111 [info] pac server listen at: 127.0.0.1:2333
2019-02-14 10:09:12:112 [info] http proxy server listen at: 127.0.0.1:12333
2019-02-14 10:09:13:182 [error] 2019-02-14 10:09:12 INFO     util.py:85 loading libcrypto from C:\WINDOWS\system32\libcrypto.dll
2019-02-14 10:09:12 INFO     local.py:50 local start with protocol[origin] password [zhouzhu85] method [rc4-md5] obfs [plain] obfs_param []
2019-02-14 10:09:12 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-02-14 10:09:12 INFO     asyncdns.py:324 dns server: [('8.8.4.4', 53), ('8.8.8.8', 53)]

2019-02-14 10:09:16:726 [info] Update for version 0.2.6 is not available (latest version: 0.2.6, downgrade is disallowed).

**Comment by erguotou520** [comment]
似乎设置代理的时候错了，但这不影响使用，pac设置失败的话可以自己手动设置

**Comment by zhouzhu85** [comment]
好的

**Comment by lh123lh** [comment]
我也是这个问题，相同的节点，ssrr可以用，electron-ssr就用不了
