### ISSUE TITLE
windows10无法代理，切换全局也无济于事，老板SSR可以

### ISSUE THREAD

**Issue by BestRicky** [erguotou520/electron-ssr#299]
2019-02-19 12:43:09:394 [info] Checking for update
2019-02-19 12:43:10:722 [info] Generated new staging user ID: 4944e467-3162-5ae3-83c8-27ef71f07781
2019-02-19 12:43:16:761 [info] start download ssr
2019-02-19 12:43:18:516 [info] ssr download success
2019-02-19 12:43:18:547 [error] Error: Command failed: C:\Program Files (x86)\electron-ssr\sysproxy.exe pac ""
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:603:13)
    at execSync (child_process.js:643:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:687:22)
    at j (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56151)
    at P (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56432)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:77481)
    at e.__tryOrUnsub (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:11312)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:10590)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:17837)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at m (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:55286)

2019-02-19 12:43:19:395 [info] Update for version 0.2.6 is not available (latest version: 0.2.6, downgrade is disallowed).
2019-02-19 12:43:20:571 [error] Error: Command failed: C:\Program Files (x86)\electron-ssr\sysproxy.exe pac ""
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:603:13)
    at execSync (child_process.js:643:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:687:22)
    at j (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56151)
    at P (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56432)
    at App.<anonymous> (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:84124)
    at emitOne (events.js:120:20)
    at App.emit (events.js:210:7)
    at App.emitter.emit.args [as emit] (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\@sentry\electron\src\main\integrations\electron.ts:65:14)
    at J (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:58849)
    at MenuItem.click (C:\Program Files (x86)\electron-ssr\resources\electron.asar\browser\api\menu-item.js:52:9)
    at Function.executeCommand (C:\Program Files (x86)\electron-ssr\resources\electron.asar\browser\api\menu.js:34:15)

2019-02-19 12:49:32:139 [info] Checking for update
2019-02-19 12:49:34:456 [error] Error: Error: net::ERR_NAME_NOT_RESOLVED
    at CancellationToken.createPromise (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
    at ElectronHttpExecutor.doApiRequest (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:84:30)
    at ElectronHttpExecutor.request (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:74:17)
    at GitHubProvider.httpRequest (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\Provider.ts:29:26)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\GitHubProvider.ts:38:41
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\GitHubProvider.ts:35:25)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:308:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater.getUpdateInfo (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:298:32)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:312:35
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:311:34)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:283:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:278:33)
    at NsisUpdater.checkForUpdates (C:\Program Files (x86)\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:217:35)
    at W (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:59493)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:83314
    at <anonymous>
2019-02-19 12:49:36:226 [info] run command: python C:\Users\**\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s 127.0.0.1 -p 8388 -k ****** -m aes-256-cfb -O origin -o plain -b 127.0.0.1 -l 1080
2019-02-19 12:49:36:231 [info] pac server listen at: 127.0.0.1:2333
2019-02-19 12:49:36:231 [info] http proxy server listen at: 127.0.0.1:12333
2019-02-19 12:49:36:540 [error] 2019-02-19 12:49:36 WARNING  shell.py:113 warning: server set to listen on 127.0.0.1:8388, are you sure?

2019-02-19 12:49:36:556 [info] IPv6 support

2019-02-19 12:49:36:556 [error] Traceback (most recent call last):
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\crypto\openssl.py", line 89, in __init__
    load_openssl()
  File "C:\Users\�����\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\crypto\openssl.py", line 41, in load_openssl
    raise Exception('libcrypto(OpenSSL) not found')
Exception: libcrypto(OpenSSL) not found

2019-02-19 12:49:37:584 [error] Error: Command failed: C:\Program Files (x86)\electron-ssr\sysproxy.exe pac ""
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:603:13)
    at execSync (child_process.js:643:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:687:22)
    at j (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56151)
    at P (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56432)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:77481)
    at e.__tryOrUnsub (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:11312)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:10590)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:17837)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at m (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:55286)

2019-02-19 12:49:37:586 [info] Kill client
2019-02-19 12:49:37:587 [info] pac server closed.
2019-02-19 12:49:37:587 [info] http proxy server closed.
2019-02-19 12:49:37:590 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: kill ESRCH
2019-02-19 12:49:37:598 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_NAME_NOT_RESOLVED
2019-02-19 12:49:37:598 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_NAME_NOT_RESOLVED
2019-02-19 12:49:37:600 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_NAME_NOT_RESOLVED
2019-02-19 12:49:37:600 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_NAME_NOT_RESOLVED
2019-02-19 12:49:42:601 [error] 进程 14612 可能无法关闭
2019-02-19 12:51:51:828 [info] Kill client
2019-02-19 12:51:51:844 [info] pac server listen at: 127.0.0.1:2333
2019-02-19 12:51:51:844 [info] http proxy server listen at: 127.0.0.1:12333
2019-02-19 12:51:51:844 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: kill ESRCH
2019-02-19 12:51:52:889 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-02-19 12:51:52:889 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-02-19 12:51:56:853 [error] 进程 14612 可能无法关闭
2019-02-19 12:58:30:879 [error] Error: Command failed: C:\Program Files (x86)\electron-ssr\sysproxy.exe pac ""
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:603:13)
    at execSync (child_process.js:643:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:687:22)
    at j (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56151)
    at P (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56432)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:77481)
    at e.__tryOrUnsub (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:11312)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:10590)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:17837)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at m (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:55286)

2019-02-19 12:58:30:883 [info] Kill client
2019-02-19 12:58:30:886 [info] pac server closed.
2019-02-19 12:58:30:886 [info] http proxy server closed.
2019-02-19 12:58:30:886 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: kill EPERM
2019-02-19 12:58:31:689 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-02-19 12:58:31:690 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-02-19 12:58:32:293 [info] Kill client
2019-02-19 12:58:32:304 [info] pac server listen at: 127.0.0.1:2333
2019-02-19 12:58:32:304 [info] http proxy server listen at: 127.0.0.1:12333
2019-02-19 12:58:32:305 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: kill EPERM
2019-02-19 12:58:32:568 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-02-19 12:58:32:569 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting

**Comment by lengthmin** [comment]
我也是这样，看日志应该是因为路径乱码了。
![image](https://user-images.githubusercontent.com/13938334/53169360-f8edea00-3617-11e9-91c8-d889997772bb.png)

![image](https://user-images.githubusercontent.com/13938334/53169365-fab7ad80-3617-11e9-8142-74bf5ca691f2.png)

**Comment by erguotou520** [comment]
不要用中文路径

**Comment by lengthmin** [comment]
应该是路径有空格的问题。

**Comment by wrdcz** [comment]
同样的问题 没有用中文路径 还是不行

**Comment by wrdcz** [comment]
同样的问题 无中文路径 无法连上 尝试链接则日志新增报错

2019-03-16 00:16:10:779 [info] Kill client
2019-03-16 00:16:10:799 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: kill ESRCH
2019-03-16 00:16:12:867 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-03-16 00:16:12:867 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-03-16 00:16:15:781 [error] 进程 11600 可能无法关闭
