### ISSUE TITLE
libsodium not found

### ISSUE THREAD

**Issue by githublirui** [erguotou520/electron-ssr#307]
2019-02-26 16:51:32:532 [info] Checking for update
2019-02-26 16:51:32:783 [error] Error: Command failed: C:\Program Files (x86)\electron-ssr\sysproxy.exe pac http://127.0.0.1:2333/proxy.pac
'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
    at checkExecSyncError (child_process.js:603:13)
    at execSync (child_process.js:643:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:687:22)
    at j (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56151)
    at C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56722
    at E (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:56727)
    at M (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:57182)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:77453)
    at e.__tryOrUnsub (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:11312)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:10590)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9316)
    at e.next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:17837)
    at e._next (C:\Program Files (x86)\electron-ssr\resources\app.asar\dist\electron\main.js:1:9645)

2019-02-26 16:51:32:836 [info] run command: python C:\Users\lirui\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s 149.129.66.119 -p 3389 -k ****** -m chacha20-ietf -O  -b 127.0.0.1 -l 1080
2019-02-26 16:51:32:846 [info] pac server listen at: 127.0.0.1:2333
2019-02-26 16:51:32:846 [info] http proxy server listen at: 127.0.0.1:12333
2019-02-26 16:51:33:924 [info] IPv6 support

2019-02-26 16:51:33:925 [error] Traceback (most recent call last):
  File "C:\Users\lirui\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\lirui\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\lirui\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\lirui\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\lirui\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\lirui\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\lirui\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\lirui\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "C:\Users\lirui\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found

2019-02-26 16:51:38:470 [info] Update for version 0.2.6 is not available (latest version: 0.2.6, downgrade is disallowed).

**Comment by erguotou520** [comment]
请查看FAQ
