### ISSUE TITLE
无法代理

### ISSUE THREAD

**Issue by wrdcz** [erguotou520/electron-ssr#324]
## Your os

Win10 1809 17763.379
## The version of electron-ssr

0.2.6
## What's the problem

前一段时间可以正常代理 现在开启后无法访问网站 无论是pac模式还是全局模式 使用其他版本SSRR可代理成功
## App log here

```
2019-03-16 00:14:22:524 [info] Checking for update
2019-03-16 00:14:22:713 [info] last update time: Sat Mar 16 2019 00:14:22 GMT+0800 (China Standard Time)
2019-03-16 00:14:22:838 [info] run command: python C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s twa02.efan.men -p 55701 -k ****** -m aes-256-cfb -O origin -o plain -b 127.0.0.1 -l 1080
2019-03-16 00:14:22:842 [info] pac server listen at: 127.0.0.1:2333
2019-03-16 00:14:22:862 [info] next subscribe update time: Sun Mar 17 2019 00:14:22 GMT+0800 (China Standard Time)
2019-03-16 00:14:23:980 [info] IPv6 support

2019-03-16 00:14:23:981 [error] Traceback (most recent call last):
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\openssl.py", line 89, in __init__
    load_openssl()
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\openssl.py", line 39, in load_openssl
    'libcrypto')
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\util.py", line 83, in find_library
    lib = CDLL(path)
  File "D:\Program Files\python\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

2019-03-16 00:14:24:948 [error] Error: Error: net::ERR_PROXY_CONNECTION_FAILED
    at CancellationToken.createPromise (D:\app\ssr\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\CancellationToken.ts:51:12)
    at ElectronHttpExecutor.doApiRequest (D:\app\ssr\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:84:30)
    at ElectronHttpExecutor.request (D:\app\ssr\electron-ssr\resources\app.asar\node_modules\builder-util-runtime\src\httpExecutor.ts:74:17)
    at GitHubProvider.httpRequest (D:\app\ssr\electron-ssr\resources\app.asar\node_modules\electron-updater\src\Provider.ts:29:26)
    at D:\app\ssr\electron-ssr\resources\app.asar\node_modules\electron-updater\src\GitHubProvider.ts:38:41
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (D:\app\ssr\electron-ssr\resources\app.asar\node_modules\electron-updater\src\GitHubProvider.ts:35:25)
    at D:\app\ssr\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:308:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater.getUpdateInfo (D:\app\ssr\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:298:32)
    at D:\app\ssr\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:312:35
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (D:\app\ssr\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:311:34)
    at D:\app\ssr\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:283:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at NsisUpdater._checkForUpdates (D:\app\ssr\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:278:33)
    at NsisUpdater.checkForUpdates (D:\app\ssr\electron-ssr\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:217:35)
    at W (D:\app\ssr\electron-ssr\resources\app.asar\dist\electron\main.js:1:59493)
    at D:\app\ssr\electron-ssr\resources\app.asar\dist\electron\main.js:1:83314
    at <anonymous>
2019-03-16 00:16:10:779 [info] Kill client
2019-03-16 00:16:10:799 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: kill ESRCH
2019-03-16 00:16:12:867 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-03-16 00:16:12:867 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-03-16 00:16:15:781 [error] 进程 11600 可能无法关闭
2019-03-16 00:17:56:936 [info] Kill client
2019-03-16 00:17:56:936 [info] pac server closed.
2019-03-16 00:17:56:936 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: kill ESRCH
2019-03-16 00:17:58:175 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-03-16 00:17:58:175 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-03-16 00:18:01:947 [error] 进程 11600 可能无法关闭
2019-03-16 00:19:13:107 [info] Checking for update
2019-03-16 00:19:13:314 [info] last update time: Sat Mar 16 2019 00:19:13 GMT+0800 (China Standard Time)
2019-03-16 00:19:13:414 [info] run command: python C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s gcp2.bigrain.xyz -p 568 -k ****** -m chacha20 -O auth_aes128_sha1 -G 3401:QVC18j -o http_simple -g ae8cc3401.microsoft.com -b 127.0.0.1 -l 1080
2019-03-16 00:19:13:414 [info] pac server listen at: 127.0.0.1:2333
2019-03-16 00:19:13:440 [info] next subscribe update time: Sun Mar 17 2019 00:19:13 GMT+0800 (China Standard Time)
2019-03-16 00:19:14:520 [info] IPv6 support

2019-03-16 00:19:14:520 [error] Traceback (most recent call last):
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "C:\Users\57427\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
```

**Comment by alioox** [comment]
I encountered the same problem, install libsodium will be ok

**Comment by wrdcz** [comment]
> I encountered the same problem, install libsodium will be ok

Your proxy worked well few days ago? I have changed nothing(possibly) but it didn't work suddenly.

**Comment by wrdcz** [comment]
> I encountered the same problem, install libsodium will be ok

May I ask you how to install pre-built libsodium on windows? I google a lot but can find answer.

**Comment by erguotou520** [comment]
faq里有安装介绍
