### ISSUE TITLE
electron-ssr 0.1.1 still can't start in Fedora 26

### ISSUE THREAD

**Issue by lixiaodongsql** [erguotou520/electron-ssr#33]
I use rpm -ivh to install electron-ssr 0.1.1 in Fedora 26. But I still can't start electron-ssr 0.1.1 in Fedora 26. Thank you very much for your help. I really appreciate it.

**Comment by lixiaodongsql** [comment]
I am really sorry for posting this problem. electron-ssr 0.1.1 can start on Fedora 26. The shadowsocksr icon appears in the lower left corner of the screen. At first I didn't notice that location. But it can't scan the QR code. Thank you so much for your help again

**Comment by erguotou520** [comment]
扫描二维码时请保证整个屏幕中有且只有一个正确的二维码

**Comment by lixiaodongsql** [comment]
I can successfully scan the QR code with ShadowsocksX-NG-R8. I have already sent a URL to your Gmail address. The QR code is in the webpage whose URL I sent to you.

**Comment by lixiaodongsql** [comment]
Thank you so much for your help again.

**Comment by erguotou520** [comment]
我好像并没有收到邮件

**Comment by lixiaodongsql** [comment]
I sent the URL to erguotou525@gmail.com

**Comment by erguotou520** [comment]
确实没收到，请重新发一遍

**Comment by lixiaodongsql** [comment]
I sent the URL to your email address again.

**Comment by erguotou520** [comment]
#35 
试下更新的版本`0.1.2`

**Comment by erguotou520** [comment]
#35

**Comment by lixiaodongsql** [comment]
Thank you very much for developing the electron-ssr 0.1.2. I really appreciate it. After electron-ssr 0.1.2 scan two QR codes, it crashes. After electron-ssr scan the QR code, I select the shadowsocksR server whose connection information I scan. It seems that I can't enable the shadowsocksR server. I check the local listening port number. The listening port number is correct. But I can't circumvent China's firewall.

**Comment by erguotou520** [comment]
请在最新版中验证该问题

**Comment by Sn0rt** [comment]
```
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/ShadowsocksR客户端/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/opt/ShadowsocksR客户端/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/opt/ShadowsocksR客户端/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

```

**Comment by erguotou520** [comment]
@Sn0rt 请开新的issue，这个issue讨论的不是这个问题
