### ISSUE TITLE
centos 一直报进程无法结束

### ISSUE THREAD

**Issue by phenom-films** [erguotou520/electron-ssr#350]
一直报进程无法结束， pid总是变
已经尝试过重启， 重新下载等
下载文件的格式: electron-ssr-0.2.6.AppImage

以下是log信息：
2019-04-06 12:03:45:547 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s pmo1-server.sgateway.link -p 12478 -k ****** -m chacha20-ietf -O auth_aes128_md5 -o tls1.2_ticket_auth -g download.windowsupdate.com -b 127.0.0.1 -l 1090
2019-04-06 12:03:45:558 [info] pac server listen at: 127.0.0.1:2333
2019-04-06 12:03:45:558 [info] http proxy server listen at: 127.0.0.1:12333
2019-04-06 12:03:45:618 [info] next subscribe update time: Sun Apr 07 2019 12:03:45 GMT+0800 (CST)
2019-04-06 12:03:45:780 [info] IPv6 support

2019-04-06 12:03:45:781 [error] Traceback (most recent call last):
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 299, in get_config
    check_config(config, is_local)
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 71, in __init__
    load_libsodium()
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found

2019-04-06 12:04:19:743 [info] Kill client
2019-04-06 12:04:19:761 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: kill ESRCH
2019-04-06 12:04:20:808 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
2019-04-06 12:04:20:810 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting

**Comment by erguotou520** [comment]
`libsodium not found` 参考 faq
