### ISSUE TITLE
新手求教0.2.6版本不能ping外网

### ISSUE THREAD

**Issue by XUAN-WHUT** [erguotou520/electron-ssr#381]
Ubuntu16.04

 electron-ssr 0.2.6

安装后，导入服务器配置后，终端ping外网，不通。请问：1.是否安装的python版本问题，安装了python2.7;  2.是否安装的libsodium版本问题（libsodium-1.0.10）？

## App log here
2019-05-06 19:55:58:369 [error] 2019-05-06 19:55:58 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0

2019-05-06 19:55:58:370 [error] 2019-05-06 19:55:58 INFO     local.py:50 local start with protocol[origin] password [0] method [aes-256-cfb] obfs [plain] obfs_param []
2019-05-06 19:55:58 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-05-06 19:55:58 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

2019-05-06 19:56:01:637 [info] Kill client
2019-05-06 19:56:01:637 [info] pac server closed.
2019-05-06 19:56:01:638 [info] http proxy server closed.
2019-05-06 19:56:03:888 [info] import config from clipboard
2019-05-06 19:56:29:971 [error] Error: listen EADDRINUSE 127.0.0.1:1080
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

2019-05-06 19:56:35:759 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s usks1.twobee.bid -p 17303 -k ****** -m chacha20 -O auth_aes128_md5 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2019-05-06 19:56:35:765 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s usks1.twobee.bid -p 17303 -k ****** -m chacha20 -O auth_aes128_md5 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2019-05-06 19:56:35:769 [info] pac server listen at: 127.0.0.1:2333
2019-05-06 19:56:35:769 [info] http proxy server listen at: 127.0.0.1:12333
2019-05-06 19:56:35:831 [error] 2019-05-06 19:56:35 INFO     util.py:85 loading libsodium from libsodium.so.18
2019-05-06 19:56:35 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [fpT83l] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []

2019-05-06 19:56:35:832 [error] 2019-05-06 19:56:35 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-05-06 19:56:35 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

2019-05-06 19:56:35:841 [error] 2019-05-06 19:56:35 INFO     util.py:85 loading libsodium from libsodium.so.18

2019-05-06 19:56:35:841 [error] 2019-05-06 19:56:35 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [fpT83l] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []
2019-05-06 19:56:35 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-05-06 19:56:35 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

2019-05-06 19:56:35:842 [error] 2019-05-06 19:56:35 ERROR    shell.py:50 [Errno 98] Address already in use

2019-05-06 19:56:35:843 [info] IPv6 not support

2019-05-06 19:59:38:633 [error] 2019-05-06 19:59:38 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0

2019-05-06 19:59:39:339 [error] 2019-05-06 19:59:39 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-05-06 19:59:39 ERROR    tcprelay.py:1037 remote error, when connect to 69.171.225.13:443

2019-05-06 19:59:43:022 [error] 2019-05-06 19:59:43 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-05-06 19:59:43 ERROR    tcprelay.py:1037 remote error, when connect to 69.171.225.13:443

2019-05-06 19:59:45:277 [error] 2019-05-06 19:59:45 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-05-06 19:59:45 ERROR    tcprelay.py:1037 remote error, when connect to 69.171.225.13:443

2019-05-06 19:59:47:862 [error] 2019-05-06 19:59:47 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-05-06 19:59:47 ERROR    tcprelay.py:1037 remote error, when connect to 35.166.92.58:443

2019-05-06 19:59:47:867 [error] 2019-05-06 19:59:47 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-05-06 19:59:47 ERROR    tcprelay.py:1037 remote error, when connect to 47.96.240.190:443

2019-05-06 20:00:33:758 [info] Kill client
2019-05-06 20:04:01:329 [info] Register shortcut: toggleWindow, Ctrl+Shift+W
2019-05-06 20:04:01:338 [error] Error: listen EADDRINUSE 127.0.0.1:1080
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

2019-05-06 20:06:47:472 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s usks1.twobee.bid -p 17303 -k ****** -m chacha20 -O auth_aes128_md5 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2019-05-06 20:06:47:480 [info] pac server listen at: 127.0.0.1:2333
2019-05-06 20:06:47:481 [info] http proxy server listen at: 127.0.0.1:12333
2019-05-06 20:06:47:543 [error] 2019-05-06 20:06:47 INFO     util.py:85 loading libsodium from libsodium.so.18
2019-05-06 20:06:47 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [fpT83l] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []
2019-05-06 20:06:47 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-05-06 20:06:47 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

2019-05-06 20:07:46:175 [error] 2019-05-06 20:07:46 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0

2019-05-06 20:07:46:397 [error] 2019-05-06 20:07:46 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-05-06 20:07:46 ERROR    tcprelay.py:1037 remote error, when connect to 69.171.225.13:443

2019-05-06 20:07:46:400 [error] 2019-05-06 20:07:46 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-05-06 20:07:46 ERROR    tcprelay.py:1037 remote error, when connect to 54.186.163.246:443

2019-05-06 20:07:48:411 [error] 2019-05-06 20:07:48 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-05-06 20:07:48 ERROR    tcprelay.py:1037 remote error, when connect to 69.171.225.13:443

2019-05-06 20:07:49:220 [error] 2019-05-06 20:07:49 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-05-06 20:07:49 ERROR    tcprelay.py:1037 remote error, when connect to 69.171.225.13:443

2019-05-06 20:07:49:675 [error] 2019-05-06 20:07:49 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-05-06 20:07:49 ERROR    tcprelay.py:1037 remote error, when connect to 69.171.225.13:443

2019-05-06 20:07:50:180 [error] 2019-05-06 20:07:50 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-05-06 20:07:50 ERROR    tcprelay.py:1037 remote error, when connect to 69.171.225.13:443

2019-05-06 20:15:08:052 [info] Kill client
2019-05-06 20:15:08:088 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s usks1.twobee.bid -p 17303 -k ****** -m chacha20 -O auth_aes128_md5 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2019-05-06 20:15:08:159 [error] 2019-05-06 20:15:08 INFO     util.py:85 loading libsodium from libsodium.so.18

2019-05-06 20:15:08:160 [error] 2019-05-06 20:15:08 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [fpT83l] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []
2019-05-06 20:15:08 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-05-06 20:15:08 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

2019-05-06 20:16:12:414 [info] Kill client
2019-05-06 20:16:12:419 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s usks1.twobee.bid -p 17303 -k ****** -m chacha20 -O auth_aes128_md5 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2019-05-06 20:16:12:529 [error] 2019-05-06 20:16:12 INFO     util.py:85 loading libsodium from libsodium.so.18
2019-05-06 20:16:12 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [fpT83l] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []
2019-05-06 20:16:12 INFO     local.py:54 starting local at 127.0.0.1:1080

2019-05-06 20:16:12:530 [error] 2019-05-06 20:16:12 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

2019-05-06 20:16:13:341 [info] Kill client
2019-05-06 20:16:13:345 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s usks1.twobee.bid -p 17303 -k ****** -m chacha20 -O auth_aes128_md5 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2019-05-06 20:16:13:435 [error] 2019-05-06 20:16:13 INFO     util.py:85 loading libsodium from libsodium.so.18

2019-05-06 20:16:13:436 [error] 2019-05-06 20:16:13 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [fpT83l] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []
2019-05-06 20:16:13 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-05-06 20:16:13 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

2019-05-06 20:16:17:455 [info] Kill client
2019-05-06 20:16:17:458 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s usks1.twobee.bid -p 17303 -k ****** -m chacha20 -O auth_aes128_md5 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2019-05-06 20:16:17:556 [error] 2019-05-06 20:16:17 INFO     util.py:85 loading libsodium from libsodium.so.18

2019-05-06 20:16:17:557 [error] 2019-05-06 20:16:17 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [fpT83l] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []
2019-05-06 20:16:17 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-05-06 20:16:17 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

2019-05-06 20:16:21:574 [info] Kill client
2019-05-06 20:16:21:600 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s usks1.twobee.bid -p 17303 -k ****** -m chacha20 -O auth_aes128_md5 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2019-05-06 20:16:21:680 [error] 2019-05-06 20:16:21 INFO     util.py:85 loading libsodium from libsodium.so.18

2019-05-06 20:16:21:681 [error] 2019-05-06 20:16:21 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [fpT83l] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []
2019-05-06 20:16:21 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-05-06 20:16:21 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

2019-05-06 20:16:25:194 [info] Kill client
2019-05-06 20:16:25:199 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s usks1.twobee.bid -p 17303 -k ****** -m chacha20 -O auth_aes128_md5 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2019-05-06 20:16:25:274 [error] 2019-05-06 20:16:25 INFO     util.py:85 loading libsodium from libsodium.so.18

2019-05-06 20:16:25:282 [error] 2019-05-06 20:16:25 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [fpT83l] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []
2019-05-06 20:16:25 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-05-06 20:16:25 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

2019-05-06 20:16:39:055 [info] Kill client
2019-05-06 20:16:39:062 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s usks1.twobee.bid -p 17303 -k ****** -m chacha20 -O auth_aes128_md5 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2019-05-06 20:16:39:157 [error] 2019-05-06 20:16:39 INFO     util.py:85 loading libsodium from libsodium.so.18

2019-05-06 20:16:39:158 [error] 2019-05-06 20:16:39 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [fpT83l] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []
2019-05-06 20:16:39 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-05-06 20:16:39 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

2019-05-06 20:27:28:248 [error] 2019-05-06 20:27:28 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0

2019-05-06 20:27:28:637 [error] 2019-05-06 20:27:28 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-05-06 20:27:28 ERROR    tcprelay.py:1037 remote error, when connect to 220.181.57.216:443

2019-05-06 20:27:28:644 [error] 2019-05-06 20:27:28 ERROR    tcprelay.py:1035 [Errno 111] Connection refused

2019-05-06 20:27:28:646 [error] 2019-05-06 20:27:28 ERROR    tcprelay.py:1037 remote error, when connect to 35.164.130.113:443
2019-05-06 20:27:28 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-05-06 20:27:28 ERROR    tcprelay.py:1037 remote error, when connect to 35.164.130.113:443

2019-05-06 20:27:41:305 [error] 2019-05-06 20:27:41 ERROR    tcprelay.py:1035 [Errno 111] Connection refused
2019-05-06 20:27:41 ERROR    tcprelay.py:1037 remote error, when connect to 220.181.57.216:443

2019-05-06 20:30:37:382 [info] Register shortcut: toggleWindow, Ctrl+Shift+W
2019-05-06 20:30:37:390 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s usks1.twobee.bid -p 17303 -k ****** -m chacha20 -O auth_aes128_md5 -o tls1.2_ticket_auth -b 127.0.0.1 -l 1080
2019-05-06 20:30:37:395 [info] pac server listen at: 127.0.0.1:2333
2019-05-06 20:30:37:396 [info] http proxy server listen at: 127.0.0.1:12333
2019-05-06 20:30:37:465 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_PROXY_CONNECTION_FAILED
2019-05-06 20:30:37:522 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_PROXY_CONNECTION_FAILED
2019-05-06 20:30:37:523 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_PROXY_CONNECTION_FAILED
2019-05-06 20:30:37:545 [error] 2019-05-06 20:30:37 INFO     util.py:85 loading libsodium from libsodium.so.18

2019-05-06 20:30:37:546 [error] 2019-05-06 20:30:37 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [fpT83l] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []
2019-05-06 20:30:37 INFO     local.py:54 starting local at 127.0.0.1:1080
2019-05-06 20:30:37 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

2019-05-06 20:31:35:676 [info] http proxy server closed.
2019-05-06 20:36:28:930 [info] http proxy server listen at: 127.0.0.1:12333
2019-05-06 20:36:32:038 [info] Kill client
2019-05-06 20:36:32:040 [info] http proxy server closed.
2019-05-06 20:36:32:041 [info] http proxy server listen at: 0.0.0.0:12333
2019-05-06 20:36:32:046 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s usks1.twobee.bid -p 17303 -k ****** -m chacha20 -O auth_aes128_md5 -o tls1.2_ticket_auth -b 0.0.0.0 -l 1080
2019-05-06 20:36:32:082 [error] 2019-05-06 20:36:32 WARNING  shell.py:110 warning: local set to listen on 0.0.0.0, it's not safe

2019-05-06 20:36:32:101 [error] 2019-05-06 20:36:32 INFO     util.py:85 loading libsodium from libsodium.so.18

2019-05-06 20:36:32:102 [error] 2019-05-06 20:36:32 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [fpT83l] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []
2019-05-06 20:36:32 INFO     local.py:54 starting local at 0.0.0.0:1080
2019-05-06 20:36:32 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

2019-05-07 19:57:24:479 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_PROXY_CONNECTION_FAILED
2019-05-07 19:57:24:859 [info] Register shortcut: toggleWindow, Ctrl+Shift+W
2019-05-07 19:57:24:865 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s usks1.twobee.bid -p 17303 -k ****** -m chacha20 -O auth_aes128_md5 -o tls1.2_ticket_auth -b 0.0.0.0 -l 1080
2019-05-07 19:57:24:875 [info] pac server listen at: 0.0.0.0:2333
2019-05-07 19:57:24:876 [info] http proxy server listen at: 0.0.0.0:12333
2019-05-07 19:57:24:895 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_PROXY_CONNECTION_FAILED
2019-05-07 19:57:24:895 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_PROXY_CONNECTION_FAILED
2019-05-07 19:57:24:982 [error] 2019-05-07 19:57:24 WARNING  shell.py:110 warning: local set to listen on 0.0.0.0, it's not safe

2019-05-07 19:57:25:084 [error] 2019-05-07 19:57:25 INFO     util.py:85 loading libsodium from libsodium.so.18

2019-05-07 19:57:25:092 [error] 2019-05-07 19:57:25 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [fpT83l] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []
2019-05-07 19:57:25 INFO     local.py:54 starting local at 0.0.0.0:1080
2019-05-07 19:57:25 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

2019-05-07 19:59:20:180 [info] Kill client
2019-05-07 19:59:42:472 [info] Register shortcut: toggleWindow, Ctrl+Shift+W
2019-05-07 19:59:42:493 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s usks1.twobee.bid -p 17303 -k ****** -m chacha20 -O auth_aes128_md5 -o tls1.2_ticket_auth -b 0.0.0.0 -l 1080
2019-05-07 19:59:42:501 [info] pac server listen at: 0.0.0.0:2333
2019-05-07 19:59:42:501 [info] http proxy server listen at: 0.0.0.0:12333
2019-05-07 19:59:42:537 [error] 2019-05-07 19:59:42 WARNING  shell.py:110 warning: local set to listen on 0.0.0.0, it's not safe

2019-05-07 19:59:42:579 [error] 2019-05-07 19:59:42 INFO     util.py:85 loading libsodium from libsodium.so.18

**Comment by erguotou520** [comment]
好像http代理服务有问题

**Comment by XUAN-WHUT** [comment]
方便加个微信或者QQ不，帮忙配置一下，感激不尽~

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
