### ISSUE TITLE
请问刚安装win客户端的时候，ssr的目录怎么填

### ISSUE THREAD

**Issue by JadeVane** [erguotou520/electron-ssr#57]
给的网址说已经没有项目了，但是没有目录又用不了客户端，小白不懂轻喷

**Comment by erguotou520** [comment]
使用备份项目 https://github.com/shadowsocksr-backup/shadowsocksr/tree/dev

**Comment by JadeVane** [comment]
服务器端已经设置好了，本地客户端连接之后，在chrome设置了SwitchyOmega代理：socks5、127.0.0.1、1080端口，但是上不去外网是什么原因？是否和我之前安装过ss有关？
配置文件/etc/shadowsocks.json内容如下：
```
{
    "server":"0.0.0.0",
    "server_ipv6":"[::]",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "port_password":{
         "9605":"960522"
    },
    "timeout":120,
    "method":"chacha20-ietf",
    "protocol":"auth_sha1_v4",
    "protocol_param":"",
    "obfs":"plain",
    "obfs_param":"",
    "redirect":"",
    "dns_ipv6":false,
    "fast_open":false,
    "workers":1
}
```
这是开启ssr时的提示：
```
[root@localhost ~]# /etc/init.d/shadowsocks start
IPv6 not support
2018-01-18 19:00:45 INFO     util.py:85 loading libsodium from libsodium.so.23
2018-01-18 19:00:45 INFO     shell.py:72 ShadowsocksR 3.0.0
started
Starting ShadowsocksR success
```
本地客户端设置如下：
![image](https://user-images.githubusercontent.com/34258753/35095115-5ac313f2-fc82-11e7-91bd-19dce221a860.png)

**Comment by erguotou520** [comment]
看下日志，菜单-查看日志

**Comment by JadeVane** [comment]
@erguotou520  日志是这样的，好像问题不少：
```
2018-1-18 20:12:48 stdout:
IPv6 support
2018-1-18 20:12:48 stderr:
Traceback (most recent call last):
  File "D:\shadowsocksr-dev\shadowsocks\local.py", line 81, in <module>
    main()
  File "D:\shadowsocksr-dev\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\crypto\sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
```

**Comment by erguotou520** [comment]
`libsodium`缺少 自己找下自己系统怎么安装这个

**Comment by teffy** [comment]
这有安装 libsodium 的shell
https://gist.github.com/jonathanpmartins/2510f38abee1e65c6d92

**Comment by JadeVane** [comment]
@teffy 感谢，不过我这里打不开这个网址，请问是win系统下的吗

**Comment by JadeVane** [comment]
@erguotou520 这几天找了一下，我是下载到了libsodium的文件，但是确实不知道该怎么用，在这里下载的https://github.com/jedisct1/libsodium，这种事还要来麻烦你实在不好意思

**Comment by erguotou520** [comment]
什么系统？
加TG群 https://t.me/electron_ssr 交流方便点

**Comment by JadeVane** [comment]
win10 64位，上面那个网址打不开

**Comment by erguotou520** [comment]
参考
- https://doub.io/ss-jc51/
- https://doub.io/ss-jc45/ (搜libsodium)
- https://lcbk.net/6510.html

**Comment by JadeVane** [comment]
感谢，这几个文件已经放进去了，对应的32位也放了， 但是有新的报错
```
2018-1-23 17:0:29 stdout:
IPv6 support
2018-1-23 17:0:29 stderr:
Traceback (most recent call last):
  File "D:\shadowsocksr-dev\shadowsocks\local.py", line 81, in <module>
    main()
  File "D:\shadowsocksr-dev\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\crypto\sodium.py", line 40, in load_libsodium
    'libsodium')
  File "D:\shadowsocksr-dev\shadowsocks\..\shadowsocks\crypto\util.py", line 83, in find_library
    lib = CDLL(path)
  File "C:\Users\BENBEN\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 ������Ч�� Win32 Ӧ�ó���
```

**Comment by erguotou520** [comment]
这个错误还是`ssr-python`的 建议先用命令行测试下

**Comment by JadeVane** [comment]
鼓捣了一下，已经解决了，感谢作者这段时间来的热心帮助
