### ISSUE TITLE
Win10 16299 无法联网，无法正常退出

### ISSUE THREAD

**Issue by peter17ji** [erguotou520/electron-ssr#70]
## Your os

Win10 16299.192
## The version of electron-ssr

v0.2.0-beta-2
## What's the problem

**无法正常退出，只能用任务管理器杀掉；无法联网，提示libsodium缺失。**
## App log here

2018-1-8 16:17:11 stdout:
IPv6 not support
usage: sslocal [OPTION]...
A fast tunnel proxy that helps you bypass firewalls.

You can supply configurations via either config file or command line arguments.

Proxy options:
  -c CONFIG              path to config file
  -s SERVER_ADDR         server address
  -p SERVER_PORT         server port, default: 8388
  -b LOCAL_ADDR          local binding address, default: 127.0.0.1
  -l LOCAL_PORT          local port, default: 1080
  -k PASSWORD            password
  -m METHOD              encryption method, default: aes-256-cfb
  -o OBFS                obfsplugin, default: http_simple
  -t TIMEOUT             timeout in seconds, default: 300
  --fast-open            use TCP_FASTOPEN, requires Linux 3.7+

General options:
  -h, --help             show this help message and exit
  -d start/stop/restart  daemon mode
  --pid-file PID_FILE    pid file for daemon mode
  --log-file LOG_FILE    log file for daemon mode
  --user USER            username to run as
  -v, -vv                verbose mode
  -q, -qq                quiet mode, only show warnings/errors
  --version              show version information

Online help: <https://github.com/shadowsocks/shadowsocks>

2018-1-8 16:17:11 stderr:
option -O not recognized
2018-1-8 16:18:10 stdout:
IPv6 not support
usage: sslocal [OPTION]...
A fast tunnel proxy that helps you bypass firewalls.

You can supply configurations via either config file or command line arguments.

Proxy options:
  -c CONFIG              path to config file
  -s SERVER_ADDR         server address
  -p SERVER_PORT         server port, default: 8388
  -b LOCAL_ADDR          local binding address, default: 127.0.0.1
  -l LOCAL_PORT          local port, default: 1080
  -k PASSWORD            password
  -m METHOD              encryption method, default: aes-256-cfb
  -o OBFS                obfsplugin, default: http_simple
  -t TIMEOUT             timeout in seconds, default: 300
  --fast-open            use TCP_FASTOPEN, requires Linux 3.7+

General options:
  -h, --help             show this help message and exit
  -d start/stop/restart  daemon mode
  --pid-file PID_FILE    pid file for daemon mode
  --log-file LOG_FILE    log file for daemon mode
  --user USER            username to run as
  -v, -vv                verbose mode
  -q, -qq                quiet mode, only show warnings/errors
  --version              show version information

Online help: <https://github.com/shadowsocks/shadowsocks>

2018-1-8 16:18:10 stderr:
option -O not recognized
2018-1-8 16:19:2 stderr:
option -O not recognized
2018-1-8 16:19:2 stdout:
IPv6 not support
usage: sslocal [OPTION]...
A fast tunnel proxy that helps you bypass firewalls.

You can supply configurations via either config file or command line arguments.

Proxy options:
  -c CONFIG              path to config file
  -s SERVER_ADDR         server address
  -p SERVER_PORT         server port, default: 8388
  -b LOCAL_ADDR          local binding address, default: 127.0.0.1
  -l LOCAL_PORT          local port, default: 1080
  -k PASSWORD            password
  -m METHOD              encryption method, default: aes-256-cfb
  -o OBFS                obfsplugin, default: http_simple
  -t TIMEOUT             timeout in seconds, default: 300
  --fast-open            use TCP_FASTOPEN, requires Linux 3.7+

General options:
  -h, --help             show this help message and exit
  -d start/stop/restart  daemon mode
  --pid-file PID_FILE    pid file for daemon mode
  --log-file LOG_FILE    log file for daemon mode
  --user USER            username to run as
  -v, -vv                verbose mode
  -q, -qq                quiet mode, only show warnings/errors
  --version              show version information

Online help: <https://github.com/shadowsocks/shadowsocks>

2018-1-8 16:19:33 stdout:
IPv6 not support
usage: sslocal [OPTION]...
A fast tunnel proxy that helps you bypass firewalls.

You can supply configurations via either config file or command line arguments.

Proxy options:
  -c CONFIG              path to config file
  -s SERVER_ADDR         server address
  -p SERVER_PORT         server port, default: 8388
  -b LOCAL_ADDR          local binding address, default: 127.0.0.1
  -l LOCAL_PORT          local port, default: 1080
  -k PASSWORD            password
  -m METHOD              encryption method, default: aes-256-cfb
  -o OBFS                obfsplugin, default: http_simple
  -t TIMEOUT             timeout in seconds, default: 300
  --fast-open            use TCP_FASTOPEN, requires Linux 3.7+

General options:
  -h, --help             show this help message and exit
  -d start/stop/restart  daemon mode
  --pid-file PID_FILE    pid file for daemon mode
  --log-file LOG_FILE    log file for daemon mode
  --user USER            username to run as
  -v, -vv                verbose mode
  -q, -qq                quiet mode, only show warnings/errors
  --version              show version information

Online help: <https://github.com/shadowsocks/shadowsocks>

2018-1-8 16:19:33 stderr:
option -O not recognized
2018-02-06T10:02:38+0800 <info> main.js:1 () file ensured
2018-02-06T10:02:47+0800 <debug> main.js:1 (EventEmitter.<anonymous>) start download ssr
2018-02-06T10:02:51+0800 <debug> main.js:1 () ssr download success
2018-02-06T10:04:25+0800 <debug> main.js:1 () run command: python C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s 咳咳咳
2018-02-06T10:04:26+0800 <log> events.js:101 (emitOne) IPv6 support

2018-02-06T10:04:26+0800 <error> events.js:101 (emitOne) Traceback (most recent call last):
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\crypto\sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found

2018-02-06T10:04:26+0800 <log> events.js:111 (emitTwo) 1 null
2018-02-06T10:05:18+0800 <log> main.js:1 () Kill python client
2018-02-06T10:05:23+0800 <log> main.js:1 () Kill python client
2018-02-06T10:05:52+0800 <debug> main.js:1 () start download pac
2018-02-06T10:06:28+0800 <log> main.js:1 () Kill python client
2018-02-06T10:06:31+0800 <log> main.js:1 () Kill python client
2018-02-06T10:06:33+0800 <log> main.js:1 () Kill python client
2018-02-06T10:06:58+0800 <info> main.js:1 () file ensured
2018-02-06T10:06:58+0800 <debug> main.js:1 (Server.<anonymous>) pac server listen at: 127.0.0.1:2333
2018-02-06T10:06:58+0800 <debug> main.js:1 (Server.<anonymous>) http proxy server listen at: 127.0.0.1:12333
2018-02-06T10:07:04+0800 <debug> main.js:1 () run command: python C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s 咳咳咳
2018-02-06T10:07:04+0800 <log> events.js:101 (emitOne) IPv6 support

2018-02-06T10:07:04+0800 <error> events.js:101 (emitOne) Traceback (most recent call last):
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\crypto\sodium.py", line 71, in __init__
    load_libsodium()
  File "C:\Users\peter\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\../shadowsocks\crypto\sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found

2018-02-06T10:07:04+0800 <log> events.js:111 (emitTwo) 1 null
2018-02-06T10:07:27+0800 <log> main.js:1 () Kill python client
2018-02-06T10:07:27+0800 <debug> main.js:1 () http proxy server closed.
2018-02-06T10:07:27+0800 <debug> main.js:1 (Server.<anonymous>) http proxy server listen at: 0.0.0.0:12333
2018-02-06T10:07:46+0800 <debug> main.js:1 () start download pac
2018-02-06T10:10:57+0800 <log> main.js:1 () Kill python client
2018-02-06T10:11:37+0800 <log> main.js:1 () Kill python client
2018-02-06T10:11:41+0800 <log> main.js:1 () Kill python client
//实际上关不掉

**Comment by peter17ji** [comment]
错误日志Exception: libsodium not found
该错误是因为当前系统缺少libsodium库导致，Mac下使用brew install libsodium安装，Ubuntu可参考https://gist.github.com/jonathanpmartins/2510f38abee1e65c6d92安装，其它系统请自行搜索。
不过无法退出的问题在FAQ里没有。

**Comment by peter17ji** [comment]
Windows的话把libsodium官方git里面下载到的dll放入windows\system32文件夹即可

**Comment by peter17ji** [comment]
还要确认python是32位或64位

**Comment by printempw** [comment]
我也遇到无法退出的问题了，右键托盘 -> 点击「退出」按钮后应用完全没有反应，只能直接杀进程。

GIF 录屏预览如下：

![screenshot](https://i.loli.net/2018/02/11/5a7f9dded5db0.gif)

**Comment by printempw** [comment]
而且当出现「无法退出」的问题时，代理也会出现问题（无法连接）。重新启动应用后一切正常，可以连接也可以正常退出。

我猜可能是应用内部抛了异常没解决好？

**Comment by erguotou520** [comment]
请描述无法退出的前置场景

**Comment by printempw** [comment]
并没有进行什么特殊操作，有时候突然代理变得无法连接，此时尝试在托盘菜单退出程序时通常都会失效。日志中有如下字样：

![log screenshot](https://i.loli.net/2018/02/11/5a80179c10bf7.jpg)

日志文件中的中文字符不知道是什么情况，尝试了各种编码都无法正确显示。从错误代码推断应该是：

```
[WinError 10054] 远程主机强迫关闭了一个现有的连接
```

**Comment by erguotou520** [comment]
connection reset by peer?

**Comment by erguotou520** [comment]
先尝试使用python命令行运行下 看下是否正常

**Comment by printempw** [comment]
这只是偶发情况，不是一直被 connection reset by peer 的。用 python 命令行或者重启 electron-ssr 后代理均正常运行。

**Comment by erguotou520** [comment]
那重启后就一直正常了？

**Comment by printempw** [comment]
是的，之后一直正常（从我最开始的发言到现在）。

从 @peter17ji 的日志来看，他似乎也是因为 ssr-python 后端抛出异常（他的异常是 `libsodium not found` 而我的是 `connection reset by peer`），可否假定当后端抛出异常时 electron-ssr 也会出现「代理失效，且从托盘菜单无法退出」的情况？

一点想法，未经验证。

**Comment by erguotou520** [comment]
有这个可能

**Comment by printempw** [comment]
再次出现了同样的症状：

![Snipaste_2018-02-11_21-49-40.png](https://i.loli.net/2018/02/11/5a804aaa12182.png)
![ssr2.gif](https://i.loli.net/2018/02/11/5a804a9fd71b6.gif)

**Comment by erguotou520** [comment]
`0.2.0`版本应该已修复这个问题

**Comment by erguotou520** [comment]
关于`libsodium`的问题已更新至FAQ
