### ISSUE TITLE
代理未成功启动

### ISSUE THREAD

**Issue by sky96111** [erguotou520/electron-ssr#79]
## What's the problem
代理启动后未生效。

## App log here
2018-03-01 21:34:50 <info> main.js:1 () file ensured
2018-03-01 21:41:03 <debug> main.js:1 (o) run command: python C:\Users\sky96111\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py -s ************* -p **** -k ******** -m aes-256-cfb -O auth_sha1_v4 -o http_simple -g cn.bing.com -b 127.0.0.1 -l 1080
2018-03-01 21:41:03 <debug> main.js:1 (Server.<anonymous>) pac server listen at: 127.0.0.1:2333
2018-03-01 21:41:03 <debug> main.js:1 (Server.<anonymous>) http proxy server listen at: 127.0.0.1:12333
IPv6 support
Traceback (most recent call last):
  File "C:\Users\sky96111\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 81, in <module>
    main()
  File "C:\Users\sky96111\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\local.py", line 43, in main
    config = shell.get_config(True)
  File "C:\Users\sky96111\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "C:\Users\sky96111\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "C:\Users\sky96111\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "C:\Users\sky96111\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "C:\Users\sky96111\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "C:\Users\sky96111\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\openssl.py", line 89, in __init__
    load_openssl()
  File "C:\Users\sky96111\AppData\Roaming\electron-ssr\shadowsocksr\shadowsocks\..\shadowsocks\crypto\openssl.py", line 41, in load_openssl
    raise Exception('libcrypto(OpenSSL) not found')
Exception: libcrypto(OpenSSL) not found
2018-03-01 21:41:11 <log> main.js:1 () Kill python client
2018-03-01 21:41:11 <debug> main.js:1 () pac server closed.
2018-03-01 21:41:11 <debug> main.js:1 () http proxy server closed.

**Comment by erguotou520** [comment]
`Exception('libcrypto(OpenSSL) not found')`是重点。ssr的问题我这里不提供解决方案，请自行搜索解决。
