### ISSUE TITLE
用不了npm test

### ISSUE THREAD

**Issue by simon300000** [erguotou520/electron-ssr#82]
## Your os
MacOS 10.13.4
node v9.7.1
cnpm 4.4.2

## The version of electron-ssr
Master

## What's the problem
npm test 会有奇怪的提示

尝试过：
装 karma-webpack，
改 test/unit/karma.conf.js 的 plugins

## App log here
```➜  electron-ssr git:(master) ✗ npm test

> electron-ssr@0.2.2 test /Users/simon3000/GitHub/electron-ssr
> npm run unit


> electron-ssr@0.2.2 unit /Users/simon3000/GitHub/electron-ssr
> karma start test/unit/karma.conf.js

14 03 2018 01:02:09.261:ERROR [preprocess]: Can not load "webpack", it is not registered!
  Perhaps you are missing some plugin?
14 03 2018 01:02:09.264:ERROR [preprocess]: Can not load "sourcemap", it is not registered!
  Perhaps you are missing some plugin?
/usr/local/lib/node_modules/karma/node_modules/.0.0.1@di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:mocha"! (Resolving: framework:mocha)
    at error (/usr/local/lib/node_modules/karma/node_modules/.0.0.1@di/lib/injector.js:22:12)
    at Object.get (/usr/local/lib/node_modules/karma/node_modules/.0.0.1@di/lib/injector.js:9:13)
    at Injector.get (/usr/local/lib/node_modules/karma/node_modules/.0.0.1@di/lib/injector.js:54:19)
    at /usr/local/lib/node_modules/karma/lib/server.js:166:20
    at Array.forEach (<anonymous>)
    at Server._start (/usr/local/lib/node_modules/karma/lib/server.js:165:21)
    at Injector.invoke (/usr/local/lib/node_modules/karma/node_modules/.0.0.1@di/lib/injector.js:75:15)
    at Server.start (/usr/local/lib/node_modules/karma/lib/server.js:126:18)
    at Object.exports.run (/usr/local/lib/node_modules/karma/lib/cli.js:283:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:660:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-ssr@0.2.2 unit: `karma start test/unit/karma.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-ssr@0.2.2 unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/simon3000/.npm/_logs/2018-03-13T17_02_09_280Z-debug.log
npm ERR! Test failed.  See above for more details.
```

**Comment by erguotou520** [comment]
emmm~ 其实 确实不能直接用，需要做一定的改动

**Comment by simon300000** [comment]
哇→_→

**Comment by erguotou520** [comment]
请使用0.2.5版本测试
