### ISSUE TITLE
win10 无法启动图形化界面

### ISSUE THREAD

**Issue by fivestrong** [erguotou520/electron-ssr#85]
## Your os

win10企业版
## The version of electron-ssr

electron-ssr-setup-0.2.2.exe
## What's the problem

安装后没有启动图形化界面，双击桌面图标无反应，但是后台启动3个进程。
通过命令行启动，第一次启动会更新，显示
```python
Checking for update
C:\Users\xxx' 锟斤拷锟斤拷锟节诧拷锟斤拷锟解部锟斤拷锟筋，也锟斤拷锟角匡拷锟斤拷锟叫的筹拷锟斤拷
锟斤拷锟斤拷锟斤拷锟斤拷锟侥硷拷锟斤拷
Update for version 0.2.2 is not available (latest version: 0.2.2, downgrade is disallowed.
```

再次启动显示
```
module.js:487
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (C:\Users\xxx\AppData\Local\Programs\electron-ssr\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.get [as dialog] (C:\Users\xxx\AppData\Local\Programs\electron-ssr\resources\electron.asar\browser\api\exports\electron.js:11:16)
    at process.<anonymous> (C:\Users\xxx\AppData\Local\Programs\electron-ssr\resources\electron.asar\browser\init.js:54:31)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process.emit (C:\Users\xxx\AppData\Local\Programs\electron-ssr\resources\app.asar\node_modules\source-map-support\source-map-support.js:453:21)
```

**Comment by erguotou520** [comment]
没有遇到过此问题，尝试自行构建？

**Comment by fivestrong** [comment]
**
![2018-03-17_182454](https://user-images.githubusercontent.com/7643380/37554249-d2cd9f3c-2a10-11e8-8ad4-378f713f3cc0.png)
![2018-03-17_182513](https://user-images.githubusercontent.com/7643380/37554254-d9aaaf16-2a10-11e8-93c8-d6541053ef18.png)

**
@erguotou520 
这是安装完exe程序以后生成的目录，根据报错感觉是不是resources目录下内容没有安装全？或者这个程序需要用到注册表什么的吗？如果从其它能够运行的windows电脑上拷贝一份过来，直接能直接双击运行吗？我在archlinux上用着效果很好，可是windows就出现这种问题。

**Comment by erguotou520** [comment]
1.尝试卸载重装
2.不要通过拷贝的方式使用
3.还不行尝试自行构建并安装

**Comment by agoodcoolman** [comment]
liunx 下怎么卸载

**Comment by erguotou520** [comment]
@agoodcoolman 请不要在别人的issue下回复非相关的问题，另外请学会如何搜索

**Comment by agoodcoolman** [comment]
@erguotou520 ok ba . 我已经解决了。
