### ISSUE TITLE
A JavaScript error occurred in the main process?

### ISSUE THREAD

**Issue by lostkf** [erguotou520/electron-ssr#91]
debian 9环境每次安装都出现这个

Uncaught Exception:
Error: Command failed: gsettings set org.gnome.system.proxy mode 'none'
/bin/sh: 1: gsettings: not found

    at checkExecSyncError (child_process.js:603:13)
    at execSync (child_process.js:643:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:687:22)
    at o (/opt/electron-ssr/resources/app.asar/dist/electron/main.js:1:55434)
    at n (/opt/electron-ssr/resources/app.asar/dist/electron/main.js:1:55706)
    at t._next (/opt/electron-ssr/resources/app.asar/dist/electron/main.js:1:56758)
    at t.__tryOrUnsub (/opt/electron-ssr/resources/app.asar/dist/electron/main.js:1:21084)
    at t.next (/opt/electron-ssr/resources/app.asar/dist/electron/main.js:1:20358)
    at t._next (/opt/electron-ssr/resources/app.asar/dist/electron/main.js:1:19412)
    at t.next (/opt/electron-ssr/resources/app.asar/dist/electron/main.js:1:19083)

**Comment by erguotou520** [comment]
那看来你的linux不支持`gsettings`
